[
  ../programs/shell
  ../programs/neovim
  ../programs/git.nix
  ../programs/github.nix
  ../programs/cmdline-tools.nix
  ../programs/opencode
  ../programs/claude
  ../programs/docker.nix
  ../programs/dev-python.nix
  ../programs/dev-js.nix
  ../programs/dev-go.nix
  ../programs/dev-db.nix
]
